name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: checkout "built" branch with content of "main"
      run: |
        git checkout -b built || git checkout built
        git pull
        git reset --hard origin/main

    - uses: jetli/wasm-pack-action@v0.4.0
    - name: Build
      run: |
        cd nicehtml_transpiler
        wasm-pack build --target web

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Commit and Push Changes
      run: |
        git add -f nicehtml_transpiler/pkg
        git commit -m "Deploying build results to new branch"
        git push origin built
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}